version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: "@slack/bolt"
    versions:
    - 3.1.1
    - 3.2.0
    - 3.3.0
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
  - dependency-name: eslint-config-airbnb-base
    versions:
    - 14.2.0
